verifica = input('Digite algo a ser verificado: ')
print(verifica.isalnum())
print(verifica.isalpha())
print('Só tem espaços? ', verifica.isnumeric())
print(verifica.isidentifier())
print(verifica.isupper())
print(verifica.isdigit())
print(verifica.islower())
print(verifica.isdecimal())
print(verifica.isdigit())
